apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: mongo-data
spec:
  storageClassName: standard
  accessModes:
    - ReadWriteOnce
  resources:
    requests:
      storage: 1Gi
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: mongodbservice
spec:
  selector:
    matchLabels:
      app: mongodbservice
  template:
    metadata:
      labels:
        app: mongodbservice
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: mongo
        ports:
        - containerPort: 27017
        env:
        - name: MONGO_INITDB_ROOT_USERNAME
          valueFrom:
            secretKeyRef:
              name: mongo-creds
              key: username
        - name: MONGO_INITDB_ROOT_PASSWORD
          valueFrom:
            secretKeyRef:
              name: mongo-creds
              key: password
        - name: MONGO_INITDB_DATABASE
          value: users
        resources:
          requests:
            cpu: 200m
            memory: 1Gi
          limits:
            cpu: 300m
            memory: 1Gi
        readinessProbe:
          initialDelaySeconds: 20
          periodSeconds: 15
          exec:
            command: 
              - mongo
              - --disableImplicitSessions
              - --eval
              - "db.adminCommand('ping')"
        livenessProbe:
          initialDelaySeconds: 20
          periodSeconds: 15
          exec:
            command: 
              - mongo
              - --disableImplicitSessions
              - --eval
              - "db.adminCommand('ping')"
        volumeMounts:
        - name: mongodb-storage
          mountPath: /data/db
      volumes:
      - name: mongodb-storage
        persistentVolumeClaim:
          claimName: mongo-data
---
apiVersion: v1
kind: Service
metadata:
  name: mongodbservice
spec:
  type: ClusterIP
  selector:
    app: mongodbservice
  ports:
  - name: api
    port: 27017
    targetPort: 27017
