apiVersion: apps/v1
kind: Deployment
metadata:
  name: redisservice
spec:
  selector:
    matchLabels:
      app: redisservice
  template:
    metadata:
      labels:
        app: redisservice
    spec:
      serviceAccountName: default
      terminationGracePeriodSeconds: 5
      containers:
      - name: server
        image: redis
        ports:
        - containerPort: 6379
        resources:
          requests:
            cpu: 200m
            memory: 500Mi
          limits:
            cpu: 300m
            memory: 500Mi
        readinessProbe:
          initialDelaySeconds: 20
          periodSeconds: 15
          exec:
            command: ["redis-cli", "ping"]
        livenessProbe:
          initialDelaySeconds: 20
          periodSeconds: 15
          exec:
            command: ["redis-cli", "ping"]
---
apiVersion: v1
kind: Service
metadata:
  name: redisservice
spec:
  type: ClusterIP
  selector:
    app: redisservice
  ports:
  - name: api
    port: 6379
    targetPort: 6379
